---
title: "07.02. Polynomial Regression with Binomial Response"
output: html_notebook
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 1. logistic regression
```{r}
library(ISLR)
library(stats)
attach(Wage)
agelims = range(age)
age.grid = seq(from = agelims[1], to=agelims[2])
fit = glm(I(wage > 250) ~ poly(age, 4), data = Wage, family = "binomial")
preds = predict(fit, newdata = list(age = age.grid), se = T, type = "response")
```
# 2. plot the fit
```{r}
plot(age, I(wage > 250), xlim = agelims, type = "n", ylim = c(0, 0.2))
points(jitter(age), I((wage > 250) / 5), cex = 1, pch = "|", col = "darkgrey") # pcl:plot character; jitter: add noise to var
lines(age.grid, preds$fit, col = "blue", lwd = 2)

se.band = cbind(preds$fit + 2 * preds$se.fit, preds$fit - 2 *preds$se.fit)

pfit = exp(preds$fit) / (1 + exp(preds$fit))
se.bands.logit = cbind(preds$fit + 2 * preds$se.fit, preds$fit - 2 * preds$se.fit)
se.bands = exp(se.bands.logit) / (1 + exp(se.bands.logit))
```
```{r}
detach(Wage)
```

