---
title: "10.07. Time Series Prediction"
output: html_notebook
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
old_path <- Sys.getenv("PATH")
new_path <- paste(
  "C:/Users/dell/miniconda3/envs/r-reticulate/Library/bin",
  "C:/Users/dell/miniconda3/envs/r-reticulate/Scripts",
  old_path,
  sep = ";"
)
```

# 1. data preparation
```{r}
library(ISLR2)
library(keras)
library(tensorflow)
library(reticulate)
use_python("C:/Users/dell/miniconda3/envs/r-reticulate/python.exe")
x.data <- data.matrix(
  NYSE[, c("DJ_return", "log_volume", "log_volatility")]
)
y <- NYSE[, "train"]
x <- scale(x.data)
```

# 2. data processing
```{r}
# 构造一个用前五天成交数据来预测当天成交量的数据集
lagm <- function(x, k = 1) {
  n <- nrow(x)
  pad <- matrix(NA, k, ncol(x))
  rbind(pad, x[1:(n - k),])
}
arframe <- data.frame(log_volume = x[, "log_volume"], L1 = lagm(x, 1), L2 = lagm(x, 2), L3 = lagm(x, 3), L4 = lagm(x, 4), L5 = lagm(x, 5))
arframe <- arframe[-(1:5),]
y <- y[-(1:5)]
```

# 3. lm
```{r}
lm.fit <- lm(log_volume~., data = arframe[y,])
lm.pred <- predict(lm.fit, arframe[!y,])
v <- var(arframe[!y, "log_volume"])
1 - mean((lm.pred - arframe[!y, "log_volume"])^2) / v
```

# 4. lm with day_of_weak
```{r}
df <- data.frame(day = NYSE[-(1:5), "day_of_week"], arframe)
lm.fit <- lm(log_volume~., data = df[y,])
lm.pred <- predict(lm.fit, df[!y,])
v <- var(df[!y, "log_volume"])
1 - mean((lm.pred - df[!y, "log_volume"])^2) / v
```
# 5. 3 dim matrix with lags
```{r}
n <- nrow(arframe)
xrnn <- data.matrix(arframe[, -1])
xrnn <- array(xrnn, c(n, 3, 5))
xrnn <- xrnn[,,5:1]
# 转置矩阵，将自变量作为分组依据
xrnn <- aperm(xrnn, c(1, 3, 2))
```

# 5. rnn
```{r}
model <- keras_model_sequential()
model %>% layer_simple_rnn(units = 12, input_shape = list(5, 3), dropout = 0.1, recurrent_dropout = 0.1) %>% layer_dense(units = 1)
model %>% compile(optimizer = optimizer_rmsprop(), loss = "mse")
model %>% fit(xrnn[y,,], arframe[y, "log_volume"], batch_size = 64, epochs = 200, validation_data = list(xrnn[!y,,], arframe[!y, "log_volume"]))
r.pred <- predict(model, xrnn[!y,,])
1 - mean((r.pred - arframe[!y, "log_volume"]) ^ 2) / v
```



