---
title: "9.3. ROC Curves"
output: html_notebook
---

# 1. ROC function
```{r}
library(ROCR)
rocplot = function(pred, truth, ...) {
  predob = prediction(pred, truth)
  perf = performance(predob, "tpr", "fpr") # fpr: false positive rate,
  plot(perf, ...)
}
```

# 2. data preparation
```{r}
library(e1071)
set.seed(101)
x = matrix(rnorm(200 * 2), ncol = 2)
x[1:100,] = x[1:100,] + 2
x[101:150,] = x[101:150, ] - 2
y = c(rep(1, 150), rep(2, 50))
dat = data.frame(x = x,y = as.factor(y))
train = sample(200, 50)
```

# 3. svm on training dataset
```{r}
svmfit.opt = svm(y ~., data = dat[train,], kernel = "radial", gamma = 2, cost = 1, decision.values = T)
pred = predict(svmfit.opt, dat[train,], decision.values = T)
fitted = attributes(pred)$decision.values
```

# 4.plot the ROC
```{r}
rocplot(fitted, dat[train, "y"])
```

# 5. svm on test dataset
```{r}
fitted.test = attributes(predict(svmfit.opt, dat[-train,], decision.values = T))$decision.values
rocplot(fitted.test, dat[-train, "y"])
```

